spring:
  config:
    import: file:config-server/src/main/resources/config/secrets.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/allchat
    username: postgres
    password: allchat@12345

# Was searching for a bug for past 30 mins
# tomcat was running on 8080 even after assigning
# 8093 as a server port
# the bug was I had written post instead of port
# really need to get new glasses
server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0