spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dev_allchat

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0